import { Box } from "@mui/material";

const Index = () => {
  return (
    <Box sx={{ width: "100%" }}>
      <h1>Welcome to React.Js!</h1>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
      <p>This is a simple React.Js application.</p>
    </Box>
  );
};
export default Index;
